### ISSUE TITLE
negative value in padding of a prototxt to nnef conversion output

### ISSUE THREAD

**Issue by jnorwood** [KhronosGroup/NNEF-Tools#31]
I converted the SqueezeNet v1.1 deploy.prototxt from DeepScale using the nnef caffe conversion tool:
https://github.com/DeepScale/SqueezeNet/blob/master/SqueezeNet_v1.1/deploy.prototxt

The prototxt file doesn't specify the padding for the pool10 avg_pool layer, but the generated nnef file outputs some negative values (-14) , which I see from the spec is supposed to be illegal.  Has anyone else run into a similar problem?  I haven't tried to repeat it yet.

`    pool10 = avg_pool(conv10_tmp, size = [1, 1, 0, 0], stride = [1, 1, 1, 1], padding = [(0, 0), (0, 0), (0, -14), (0, -14)])
`

**Comment by gyenesvi** [comment]
If I get it right, this is the last pooling layer, which is a global average pool. The problem is actually that it is converted to an `avg_pool` with 0s in the `size`, which was an old notation for global averaging, but it is actually superseded by `mean_reduce`. The negative padding is probably a consequence of the 0 size. Anyway, we'll fix this by mapping the global average pool to `mean_reduce`, so it should result in

```
pool10 = mean_reduce(conv10_tmp, axes = [2,3])
```

**Comment by gyenesvi** [comment]
A fix has been added, it should be good now.

**Comment by jnorwood** [comment]
Ok, thanks.  I verified this is fixed.  I'm closing.
