### ISSUE TITLE
Caffe2 to NNEF conversion broadcasting issue

### ISSUE THREAD

**Issue by GeorgeARM** [KhronosGroup/NNEF-Tools#58]
Seems that the `broadcast` and `axis` parameters are not being taken into account when converting a caffe2 broadcastable operator to NNEF
e.g. https://caffe2.ai/docs/operators-catalogue.html#mul

Thus such conversions end up setting incorrect shapes for the input that is to be broadcasted.

This occurs for example in InceptionV2 model:
https://github.com/caffe2/models/tree/master/inception_v2

**Comment by gyenesvi** [comment]
You are probably right, it seems not to be taken into account. If I interpret it right from the example, and NCHW tensor and a C tensor are added/multiplied with `axis = 1`, that makes the C dim be matched to the right position.

However, the usage of the `broadcast` flag is not clear to me. What happens if `broadcast` is not set in Caffe2 but it should be? Will the model be invalid? In that case, can we just assume that the model is valid, in which case the value of the `broadcast` flag is irrelevant? Of course, the `axis` is still relevant and must be taken into account.

**Comment by GeorgeARM** [comment]
Yes I agree with you @gyenesvi, seems the API is a bit obscure there. Looking at the codebase the use of the `broadcast` in cooperation with `axis` is mentioned as `legacy` broadcasting while there is also support for automatic shape broadcasting.

https://github.com/pytorch/pytorch/blob/master/caffe2/operators/elementwise_ops.h#L148
https://github.com/pytorch/pytorch/blob/master/caffe2/operators/elementwise_ops_utils.cc#L7

Hope this helps, as myself am not familiar with the Caffe2 API

**Comment by gyenesvi** [comment]
Thanks, I believe we can make a fix that takes the `axis` into account.

**Comment by gyenesvi** [comment]
We rolled out an updated version of Caffe2 converter, it should handle this properly now. You may want to test the new converter.
