### ISSUE TITLE
option to override batch size during conversion

### ISSUE THREAD

**Issue by jnorwood** [KhronosGroup/NNEF-Tools#62]
I'd like to be able to override a trained model's batch size more easily during model conversions.  For, example,  the Squeezenet1.1 deploy model at [https://github.com/DeepScale/SqueezeNet/tree/master/SqueezeNet_v1.1](url)
has a batch size of 10.
I can go in manually and modify the dim:  10, but I just want to suggest that this would be a useful override option in caffe_to_nnef conversion...

**Comment by gyenesvi** [comment]
It makes sense, it would even make sense to be able to change the spatial size, and it should be treated in a consistent manner for all dimensions. However, there are some caveats:
* the interpretation of the dimensions depends on the operations in the network. Batch and spatial dimensions make sense for convolutional networks, but not necessarily for all networks that can be described by NNEF
* for changing dimensions, care must be taken to ensure that the network does not reference those dimensions elsewhere. For example if some operations (like reshape) reference the batch/spatial sizes in the middle of the network (meaning that the same value is baked in again), then it will not match if you just change the input size. Changing it everywhere is more complicated, and may not always be done (it might require changing associated variable shapes as well).

Furthermore, if the network description doesn't contain reference to these sizes (for example, fully convolutional, no reshapes inside), then you can just perform the change of sizes when processing NNEF, in the tool that consumes it, which might be a better place, since that's where you actually know what sizes you need in the end, not at the time of export.

**Comment by jnorwood** [comment]
ok, I'll close this.  I was just interested in the batch thing because I ran into it a couple of times.
