### ISSUE TITLE
Pooling layer issue

### ISSUE THREAD

**Issue by hansely** [KhronosGroup/NNEF-Tools#64]
Hi, I'm trying to parse my graph.nnef using the python function parse_file() as below:

attrs, ops = nnef.parse_file(inputFolder + 'graph.nnef')

My graph.nnef is converted from onnx model and has two nodes which are:

 pool2 = max_pool_layer(conv2, size=[2,2], stride=[2,2], dilation=[1,1], padding=[(0,0),(0,0)], border = 'ignore');
ip1 = matmul(pool2, ip1_w, transposeA = false, transposeB = true);

As in the specification, the max_pool_layer or avg_pool_layer calls the max_pool or avg_pool fragment as below:

fragment max_pool_layer(
    input: tensor<scalar>,
    size: integer[],
    border: string = 'constant',
    padding: (integer,integer)[] = [],
    stride: integer[] = [],
    dilation: integer[] = [] )
-> ( output: tensor<scalar> )
{
    output = max_pool(input, size = [1,1] + size, border = border,
                      padding = [(0,0), (0,0)] + padding
                                if length_of(padding) != 0 else [],
                      stride = [1,1] + stride
                                if length_of(stride) != 0 else [],
                      dilation = [1,1] + dilation
                                if length_of(dilation) != 0 else []);
}

As you can see, it adds two more dimensions to the input dimension. So in the above example, it gets a 2-D tensor and outputs a 4-D tensor.
However, the next operation which is matmul(), expects a 2-D tensor instead of 4-D tensor.
Therefore, when I run parse_file() function it gives me the following error:

_nnef.Error: Parse error in '/home/hansel/Downloads/NNEF/graph.nnef' [452:20] rank mismatch for A and B (4 vs 2).

So I've tried using max_pool instead of max_pool_layer but it requires 4-D tensor as an input.

Is there a way to do max_pool operation on 2-D tensor? Or do the max_pool operation and convert it back to 2-D tensor?

Thanks in advance.

**Comment by gyenesvi** [comment]
How do you convert to NNEF from ONNX? What tool are you using?

I believe the problem might be this. Since the output of a pooling is a 4D tensor, and matmul expects a 2D tensor, you have to insert a reshape or squeeze operation between the two. I think you should do that already in the original ONNX model, but ONNX might accept it without that if the last two dimensions of the output of pooling are 1. In this case, ONNX might automatically consider the result as a 2D tensor, and hence does not complain, but NNEF is more strict. Did you check if the ONNX model actually works? In this case, the conversion has to account for the missing reshape operation.

A note: I would discourage the usage of `max_pool_layer`, use `max_pool` instead, as `max_pool_layer` is not a standard operation, it is just an example in the NNEF spec.

**Comment by hansely** [comment]
The ONNX model is a working model and I converted ONNX_to_NNIR and NNIR_to_NNEF by using AMD's model compiler python script:

https://github.com/GPUOpen-ProfessionalCompute-Libraries/MIVisionX/tree/master/model_compiler/python

In addition, I'm pretty sure you are right. The ONNX & NNIR both accepts the tensor without a reshape or squeeze operation. However, when it comes to NNEF, it's not. 

If the user has some knowledge about these operations, they might add reshape or squeeze operations before running the conversion. However, if not, parsing will most likely fail if there is a pooling layer in the models.

Can NNEF parser be fixed to be more flexible on pooling layer as ONNX or NNIR? Or is there another way of parsing models without adding operations?

**Comment by gyenesvi** [comment]
Well, fixing the NNEF parser is technically possible, but if we changed it's behaviour, it would not comply to the NNEF specification. It would be easier to fix the NNIR_to_NNEF converter so that it automatically inserts that reshape operation in this case.

**Comment by hansely** [comment]
Alright then. I'll try fixing the NNIR to NNEF converter.
Thanks for your help.
